image: iquiw/alpine-emacs

.build: &build
  script:
    - emacs --batch --eval "(require 'org)" README.org --funcall org-html-export-to-html
    - ls
    - mkdir public
    - ls
    - mv README.html public/index.html
    - ls public
  artifacts:
    paths:
      - public


pages:
  <<: *build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:
  <<: *build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    