name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Emacs
        run: sudo apt-get update && sudo apt-get install -y emacs
      - name: Build and Deploy
        run: |
          emacs --batch --eval "(require 'org)" config.org --funcall org-html-export-to-html
          ls
          mkdir public
          ls
          mv config.html public/index.html
          ls public
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
